apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjsapp-deployment
spec:
  selector:
    matchLabels:
      app: myjsapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myjsapp
    spec:
      containers:
      - name: appjs
        image: mouagaga/myjsapp:v1.0.1
        ports:
        - containerPort: 8081

